### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by musm**
fix osx travis . Would be nice to tag after this.

### CODE REVIEW

**Comment by musm** [comment]
cc @caimichael

**Comment by musm** [comment]
bump

**Comment by caimichael** [comment]
Does this address the gcc build issue I mentioned in the comment on the travis file (and if it has been officially addressed by homebrew/the Julia core developers, could you reference the issue that you saw this in)? If not, I do not think I can merge your pull request.

**Comment by musm** [comment]
This is the current recommended solution for HDF5 dependent packages , see https://github.com/JuliaIO/HDF5.jl/blob/master/.travis.yml

**Comment by caimichael** [comment]
If you can resubmit your PR uncommenting out the osx build option for the travis file, and if it passes the build on osx, then I'll merge. But to my knowledge nothing has been done on this front yet to fix the underlying issue with gcc.

**Comment by musm** [comment]
done and all tests pass

**Comment by musm** [comment]
@caimichael  this PR has been updated and now passes as you requested.

**Comment by caimichael** [comment]
Thank you @musm! Appreciate the PR.

**Pull request merged**
