### PR TITLE
Fix minimum -> minimizer, f_minimum -> minimum, and Optim deprecation…

### PR DESCRIPTION
**Pull request by pkofod**
… warning.

Tests don't pass locally, but I am not really sure why. Maybe someone here knows if it is related.

### CODE REVIEW

**Comment by tkelman** [comment]
Does this require an Optim minimum version of 0.7?

**Comment by pkofod** [comment]
> Does this require an Optim minimum version of 0.7?

Hmm, maybe for the changes to the `MultivariateOptimizationResults` constructor. Has something started failing?

**Comment by tkelman** [comment]
Nothing broken, I'm just wondering if the new tags that include this should have minimum versions. When was the `minimum` -> `minimizer` field rename done in Optim?

**Comment by pkofod** [comment]
The fields were renamed in v7.0.0

**Comment by emoszkowski** [comment]
@tkelman, you're right - we made the changes following the update to Optim but forgot to include the update in REQUIRE. I have a pull request in with METADATA right now and made the change there; is that kosher?

**Pull request merged**
